<?php

use Drupal\wmmailable\MailableInterface;

/**
 * Implements hook_mail().
 * Sets default values for the mail.
 */
function wmmailable_mail($key, &$message, $params)
{
    if (!$params['mailable'] instanceof MailableInterface) {
        throw new \Exception('Mailable emails should be composed through the wmmailable.mailer service.');
    }

    $message['mailable'] = $params['mailable'];

    \Drupal::getContainer()->get('module_handler')
        ->alter(['wmmailable', 'wmmailable_' . $key], $params['mailable']);

    \Drupal::getContainer()->get('wmmailable.message_builder')
        ->populateMessage($message, $params['mailable']);
}

/**
 * Implements hook_theme().
 */
function wmmailable_theme()
{
    $manager = \Drupal::getContainer()->get('plugin.manager.mailable');
    $themeName = \Drupal::config('system.theme')->get('default');
    $dir = drupal_get_path('theme', $themeName) . DIRECTORY_SEPARATOR . 'templates';
    $data = [];

    foreach ($manager->getDefinitions() as $id => $definition) {
        if (!empty($definition['template'])) {
            $template = str_replace('.', DIRECTORY_SEPARATOR, $definition['template']);
        } else {
            $template = 'mail' . DIRECTORY_SEPARATOR . str_replace('_', '-', $id);
        }

        $path = $dir . DIRECTORY_SEPARATOR . $template;

        $data["wmmailable.$id"] = [
            'variables' => [
                '_data' => [],
            ],
            'path' => dirname($path),
            'template' => basename($path),
            'preprocess functions' => [
                'wmmailable_theme_set_variables',
            ],
        ];
    }

    $data['wmmailable'] = [
        'variables' => [
            'body' => [],
        ],
        'path' => drupal_get_path('module', 'wmmailable') . '/templates',
        'template' => 'mailable',
    ];

    return $data;
}

function wmmailable_theme_set_variables(&$variables)
{
    // Skip if no data is set or not set as an array
    if (!isset($variables['_data']) || !is_array($variables['_data'])) {
        return;
    }

    $variables = array_merge($variables, $variables['_data']);
    unset($variables['_data']);
}
