<?php

use Drupal\wmmailable\MailableInterface;

/**
 * Implements hook_mail().
 * Sets default values for the mail.
 */
function wmmailable_mail($key, &$message, $params)
{
    if (!$params['mailable'] instanceof MailableInterface) {
        throw new \Exception('Mailable emails should be composed through the wmmailable.mailer service.');
    }

    $message['mailable'] = $params['mailable'];

    \Drupal::getContainer()->get('module_handler')
        ->alter(['wmmailable', 'wmmailable_' . $key], $params['mailable']);

    \Drupal::getContainer()->get('wmmailable.message_builder')
        ->populateMessage($message, $params['mailable']);
}

/**
 * Implements hook_theme().
 */
function wmmailable_theme()
{
    $manager = \Drupal::getContainer()->get('plugin.manager.mailable');
    $themeName = \Drupal::config('system.theme')->get('default');
    $path = DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR . 'mail';
    $definitions = $manager->getDefinitions();
    $data = [];

    foreach ($definitions as $id => $definition) {
        $dir = drupal_get_path('theme', $themeName) . $path;
        $template = str_replace('_', '-', $id);

        $data["wmmailable.$id"] = [
            'variables' => [
                '_data' => [],
            ],
            'path' => $dir,
            'template' => $template,
            'preprocess functions' => [
                'wmmailable_theme_set_variables',
            ],
        ];
    }

    $data['wmmailable'] = [
        'variables' => [
            'body' => [],
        ],
        'path' => drupal_get_path('module', 'wmmailable') . '/templates',
        'template' => 'mailable',
    ];

    return $data;
}

function wmmailable_theme_set_variables(&$variables)
{
    // Skip if no data is set or not set as an array
    if (!isset($variables['_data']) || !is_array($variables['_data'])) {
        return;
    }

    $variables = array_merge($variables, $variables['_data']);
    unset($variables['_data']);
}
